# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tackwin/Local_Code/easybody

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tackwin/Local_Code/easybody

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tackwin/Local_Code/easybody/CMakeFiles /home/tackwin/Local_Code/easybody/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tackwin/Local_Code/easybody/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named easybody

# Build rule for target.
easybody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 easybody
.PHONY : easybody

# fast build rule for target.
easybody/fast:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/build
.PHONY : easybody/fast

src/Graphics/Graphics.o: src/Graphics/Graphics.cpp.o

.PHONY : src/Graphics/Graphics.o

# target to build an object file
src/Graphics/Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/Graphics/Graphics.cpp.o
.PHONY : src/Graphics/Graphics.cpp.o

src/Graphics/Graphics.i: src/Graphics/Graphics.cpp.i

.PHONY : src/Graphics/Graphics.i

# target to preprocess a source file
src/Graphics/Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/Graphics/Graphics.cpp.i
.PHONY : src/Graphics/Graphics.cpp.i

src/Graphics/Graphics.s: src/Graphics/Graphics.cpp.s

.PHONY : src/Graphics/Graphics.s

# target to generate assembly for a file
src/Graphics/Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/Graphics/Graphics.cpp.s
.PHONY : src/Graphics/Graphics.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/gl3w.o: src/gl3w.c.o

.PHONY : src/gl3w.o

# target to build an object file
src/gl3w.c.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/gl3w.c.o
.PHONY : src/gl3w.c.o

src/gl3w.i: src/gl3w.c.i

.PHONY : src/gl3w.i

# target to preprocess a source file
src/gl3w.c.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/gl3w.c.i
.PHONY : src/gl3w.c.i

src/gl3w.s: src/gl3w.c.s

.PHONY : src/gl3w.s

# target to generate assembly for a file
src/gl3w.c.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/gl3w.c.s
.PHONY : src/gl3w.c.s

src/glad.o: src/glad.c.o

.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i

.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s

.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/glew.o: src/glew.c.o

.PHONY : src/glew.o

# target to build an object file
src/glew.c.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/glew.c.o
.PHONY : src/glew.c.o

src/glew.i: src/glew.c.i

.PHONY : src/glew.i

# target to preprocess a source file
src/glew.c.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/glew.c.i
.PHONY : src/glew.c.i

src/glew.s: src/glew.c.s

.PHONY : src/glew.s

# target to generate assembly for a file
src/glew.c.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/glew.c.s
.PHONY : src/glew.c.s

src/imgui.o: src/imgui.cpp.o

.PHONY : src/imgui.o

# target to build an object file
src/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui.cpp.o
.PHONY : src/imgui.cpp.o

src/imgui.i: src/imgui.cpp.i

.PHONY : src/imgui.i

# target to preprocess a source file
src/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui.cpp.i
.PHONY : src/imgui.cpp.i

src/imgui.s: src/imgui.cpp.s

.PHONY : src/imgui.s

# target to generate assembly for a file
src/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui.cpp.s
.PHONY : src/imgui.cpp.s

src/imgui_demo.o: src/imgui_demo.cpp.o

.PHONY : src/imgui_demo.o

# target to build an object file
src/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_demo.cpp.o
.PHONY : src/imgui_demo.cpp.o

src/imgui_demo.i: src/imgui_demo.cpp.i

.PHONY : src/imgui_demo.i

# target to preprocess a source file
src/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_demo.cpp.i
.PHONY : src/imgui_demo.cpp.i

src/imgui_demo.s: src/imgui_demo.cpp.s

.PHONY : src/imgui_demo.s

# target to generate assembly for a file
src/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_demo.cpp.s
.PHONY : src/imgui_demo.cpp.s

src/imgui_draw.o: src/imgui_draw.cpp.o

.PHONY : src/imgui_draw.o

# target to build an object file
src/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_draw.cpp.o
.PHONY : src/imgui_draw.cpp.o

src/imgui_draw.i: src/imgui_draw.cpp.i

.PHONY : src/imgui_draw.i

# target to preprocess a source file
src/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_draw.cpp.i
.PHONY : src/imgui_draw.cpp.i

src/imgui_draw.s: src/imgui_draw.cpp.s

.PHONY : src/imgui_draw.s

# target to generate assembly for a file
src/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_draw.cpp.s
.PHONY : src/imgui_draw.cpp.s

src/imgui_impl_opengl2.o: src/imgui_impl_opengl2.cpp.o

.PHONY : src/imgui_impl_opengl2.o

# target to build an object file
src/imgui_impl_opengl2.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_opengl2.cpp.o
.PHONY : src/imgui_impl_opengl2.cpp.o

src/imgui_impl_opengl2.i: src/imgui_impl_opengl2.cpp.i

.PHONY : src/imgui_impl_opengl2.i

# target to preprocess a source file
src/imgui_impl_opengl2.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_opengl2.cpp.i
.PHONY : src/imgui_impl_opengl2.cpp.i

src/imgui_impl_opengl2.s: src/imgui_impl_opengl2.cpp.s

.PHONY : src/imgui_impl_opengl2.s

# target to generate assembly for a file
src/imgui_impl_opengl2.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_opengl2.cpp.s
.PHONY : src/imgui_impl_opengl2.cpp.s

src/imgui_impl_opengl3.o: src/imgui_impl_opengl3.cpp.o

.PHONY : src/imgui_impl_opengl3.o

# target to build an object file
src/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_opengl3.cpp.o
.PHONY : src/imgui_impl_opengl3.cpp.o

src/imgui_impl_opengl3.i: src/imgui_impl_opengl3.cpp.i

.PHONY : src/imgui_impl_opengl3.i

# target to preprocess a source file
src/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_opengl3.cpp.i
.PHONY : src/imgui_impl_opengl3.cpp.i

src/imgui_impl_opengl3.s: src/imgui_impl_opengl3.cpp.s

.PHONY : src/imgui_impl_opengl3.s

# target to generate assembly for a file
src/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_opengl3.cpp.s
.PHONY : src/imgui_impl_opengl3.cpp.s

src/imgui_impl_sdl.o: src/imgui_impl_sdl.cpp.o

.PHONY : src/imgui_impl_sdl.o

# target to build an object file
src/imgui_impl_sdl.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_sdl.cpp.o
.PHONY : src/imgui_impl_sdl.cpp.o

src/imgui_impl_sdl.i: src/imgui_impl_sdl.cpp.i

.PHONY : src/imgui_impl_sdl.i

# target to preprocess a source file
src/imgui_impl_sdl.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_sdl.cpp.i
.PHONY : src/imgui_impl_sdl.cpp.i

src/imgui_impl_sdl.s: src/imgui_impl_sdl.cpp.s

.PHONY : src/imgui_impl_sdl.s

# target to generate assembly for a file
src/imgui_impl_sdl.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_impl_sdl.cpp.s
.PHONY : src/imgui_impl_sdl.cpp.s

src/imgui_widgets.o: src/imgui_widgets.cpp.o

.PHONY : src/imgui_widgets.o

# target to build an object file
src/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_widgets.cpp.o
.PHONY : src/imgui_widgets.cpp.o

src/imgui_widgets.i: src/imgui_widgets.cpp.i

.PHONY : src/imgui_widgets.i

# target to preprocess a source file
src/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_widgets.cpp.i
.PHONY : src/imgui_widgets.cpp.i

src/imgui_widgets.s: src/imgui_widgets.cpp.s

.PHONY : src/imgui_widgets.s

# target to generate assembly for a file
src/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/easybody.dir/build.make CMakeFiles/easybody.dir/src/imgui_widgets.cpp.s
.PHONY : src/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... easybody"
	@echo "... src/Graphics/Graphics.o"
	@echo "... src/Graphics/Graphics.i"
	@echo "... src/Graphics/Graphics.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/gl3w.o"
	@echo "... src/gl3w.i"
	@echo "... src/gl3w.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/glew.o"
	@echo "... src/glew.i"
	@echo "... src/glew.s"
	@echo "... src/imgui.o"
	@echo "... src/imgui.i"
	@echo "... src/imgui.s"
	@echo "... src/imgui_demo.o"
	@echo "... src/imgui_demo.i"
	@echo "... src/imgui_demo.s"
	@echo "... src/imgui_draw.o"
	@echo "... src/imgui_draw.i"
	@echo "... src/imgui_draw.s"
	@echo "... src/imgui_impl_opengl2.o"
	@echo "... src/imgui_impl_opengl2.i"
	@echo "... src/imgui_impl_opengl2.s"
	@echo "... src/imgui_impl_opengl3.o"
	@echo "... src/imgui_impl_opengl3.i"
	@echo "... src/imgui_impl_opengl3.s"
	@echo "... src/imgui_impl_sdl.o"
	@echo "... src/imgui_impl_sdl.i"
	@echo "... src/imgui_impl_sdl.s"
	@echo "... src/imgui_widgets.o"
	@echo "... src/imgui_widgets.i"
	@echo "... src/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

